# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XEWzXedMEf7jrQ9PlPrbLA7k5KAFXPeA
"""

import random
import itertools

generated = []


def sys_generated():
    for i in range(4):
        generated.append(random.randint(0, 9))
    print(generated)
    return generated


def user_input():
    user_no = input("\n Guess the number")
    print(user_no)
    ulist = [int(user_no[0]), int(user_no[1]), int(user_no[2]), int(user_no[3])]
    print(ulist)
    return ulist


def process():
    for (x, i) in zip(n2, n1):
        if x == i:
            print("R", end='')
        if x not in n1:
            print("B", end='')
        elif x != i:
            print("Y", end='')


n = 0
n1 = sys_generated()

while n < 10:
    n2 = user_input()

    n = n + 1
    if n1 == n2:
        print("you guessed it right")
        break
    process()
else:
    print("try again")